# DDE1E5
# https://github.com/alacritty/alacritty/wiki/Color-schemes
# Colors (Arogonaut Modified)
[colors.bright]
black = "#6D7070"
blue = "#0099FF"
cyan = "#1A5276"
green = "#FF5733"
magenta = "#BA78EA"
red = "#FF4352"
white = "#363636"
yellow = "#1A5276"

[colors.cursor]
cursor = "#005f87"
text = "#FF261E"

[colors.normal]
black = "#202020"
blue = "#0087AF"
cyan = "#37CBE3"
green = "#148F77"
magenta = "#A963B8"
red = "#FF5733"
white = "#666666"
yellow = "#229954"

[colors.primary]
background = "#DDE1E5"
foreground = "#4C5B62"
