# https://github.com/alacritty/alacritty/wiki/Color-schemes
# Colors (Ayu Mirage)
[colors.bright]
black = "#686868"
blue = "#5CCFE6"
cyan = "#95E6CB"
green = "#A6CC70"
magenta = "#FFEE99"
red = "#F27983"
white = "#FFFFFF"
yellow = "#FFCC66"

[colors.normal]
black = "#191E2A"
blue = "#73D0FF"
cyan = "#95E6CB"
green = "#BAE67E"
magenta = "#FFD580"
red = "#FF3333"
white = "#C7C7C7"
yellow = "#FFA759"

[colors.primary]
background = "#202734"
foreground = "#CBCCC6"

# Cursor style
#
# Values for `style`:
#   - ▇ Block
#   - _ Underline
#   - | Beam
[cursor]
style = "Beam"

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
[env]
TERM = "xterm-256color"

[font]
# Point size
size = 8.0

[font.bold]
family = "SF Mono"
style = "Bold"

[font.bold_italic]
family = "SF Mono"
style = "Bold Italic"

[font.italic]
family = "SF Mono"
style = "Italic"

[font.normal]
family = "SF Mono"
style = "Semibold"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "Down"
mods = "Shift"

[scrolling]
history = 10000

# Window title
[window]
title = "Alacritty"

# Window dimensions (changes require restart)
[window.dimensions]
columns = 108
lines = 35

# Window padding (changes require restart)
[window.padding]
x = 15
y = 15
