# Hyprland config file.
# See https://wiki.hyprland.org/ for more info.



######################### MULTI FILE SOURCE ##########################
# https://wiki.hypr.land/Configuring/Keywords/#sourcing-multi-file
######################################################################
source=./hyprland/env.conf
source=./hyprland/monitor.conf
source=./hyprland/general.conf
source=./hyprland/exec.conf
source=./hyprland/window_rules.conf
source=./hyprland/bindings.conf

