#!/bin/sh

cmd="nautilus -w"             # File Manager Command
img_cmd="feh -. -g 512x512"   # Image Command

# Evaluate if Image
isImgParam=`echo $1 | grep -i '.*.png\|jp[e]\?g$'`
if [ "$isImgParam" != "" ];then
  $img_cmd $@ &>/dev/null &disown
else
  $cmd $@ &>/dev/null & disown
fi
exit 0
