#!/bin/sh

cmd="alacritty"


# Run attached
if [ $# -ne 0 ]; then 

  # Run Specific Directory
  if [ -d "$1" ]; then
    #$cmd -d $1 &>/dev/null & disown
    $cmd --working-directory $1 &>/dev/null & disown
  else
    $cmd $@
  fi

else  # Run un-attached
  $cmd &>/dev/null & disown
fi
exit 0
