# ######################### STARTUP APPS #############################
# ####################################################################
exec-once = swww-daemon
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = keychain
exec-once = copyq --start-server hide

# Start XDG Portal.
exec-once = ~/.config/hypr/scripts/start-xdg-desktop-portal.sh
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE

exec = ~/.config/hypr/scripts/set_random_wallpaper.sh
exec = ~/.config/dunst/reload.sh&
exec = ~/.config/hypr/scripts/waybar.sh


