# ######################### GLOBAL RULES #############################
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# ####################################################################
# windowrule {
#   name                = default-window-floats
#   match:initial_class = .*
#
#   float = on
# }

windowrule {
  name                = ueberzugpp-image-preview-window-floats
  match:initial_class = ueberzugpp.*

  float            = on
  no_initial_focus = on
}

windowrule {
  name                = file-selection-floats
  match:initial_class = xdg-desktop-portal-gtk

  float            = on
}

windowrule {
  name = no-name-no-blur
  match:class = ^()$
  match:title = ^()$

  no_blur = on
}

windowrule = match:title (Steam)

# Picture in picture always shown
windowrule {
  name                = picture-in-picture-auto-pin
  match:initial_title = (Picture in picture|Discord Popout)
  pin                 = on
  float               = on
}

# XWayland Video Bridge
# http://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/#xwayland
windowrule {
  name        = xwayland-video-bridge-fixes
  match:class = xwaylandvideobridge

  no_initial_focus = true
  no_focus         = true
  no_anim          = true
  no_blur          = true
  max_size         = 1 1
  opacity          = 0.0
}
