[[shades]]
name = "4000K"
start_time  = 19:00:00   # 7:00pm
end_time    = 20:30:00   # 8:30pm

[[shades]]
name = "3500K"
start_time  = 20:30:00   # 8:30pm
end_time    = 22:00:00   # 10:00pm

[[shades]]
name = "2700K"
start_time  = 22:00:00   # 10:00pm
end_time    = 06:00:00   # 06:00am


